### ISSUE TITLE
Inherit text color from icon color

### ISSUE THREAD

**Issue by hmnijp** [gfxholo/iconic#19]
Many people like me use themes or css that colour the folder names (like rainbow folders in anuppucin theme [github](https://github.com/AnubisNekhet/AnuPpuccin/blob/main/assets/gh-rainbow-preview.webp) ). Previously I used iconize and there the colour of the icon inherited the colour of the text. Is it possible to add the same option?

Usually it works like this... but it can also change dynamically.
```css
.nav-folder .nav-folder-title[data-path*="_TODO"] {
  --prefix-color: var(--mint);
}
```
![2024-07-13 13-54-25](https://github.com/user-attachments/assets/fff81f24-2c70-4b82-901c-75a7dc429877)

If you get lazy doing this, thanks anyway for a handy and quick alternative to iconize ! )
