### ISSUE TITLE
Collision with Ribbon Divider Plugin

### ISSUE THREAD

**Issue by not-a-feature** [gfxholo/iconic#32]
Hi,
first of all thanks for the Iconic plugin.

Unfortunately i noticed a collision with the Ribbon Divider Plugin.
https://github.com/andrewmcgivery/obsidian-ribbon-divider

Whenever i turn the "Iconic Plugin" on, the dividers disappear.

| Turned off | Turned on |
| -------|-------|
| ![grafik](https://github.com/user-attachments/assets/049dbf1b-5e0d-41d8-9d7c-985c789d9982) | ![grafik](https://github.com/user-attachments/assets/088ab11f-d278-4a4d-ae42-7026afd3bfd0) |

The Ribbon Divider Plugin is fairly simple. It just creates a new RibbonIcon
```ts
async renderDivider(divider: Divider) {
   if (document.body.hasClass("is-phone")) {
	return;
   }

   const dividerIconEl = this.addRibbonIcon(
	"",
	`ribbon-divider-${divider.id}`,
	(evt: MouseEvent) => {}
   );
   dividerIconEl.addClass("ribbon-divider");
   dividerIconEl.addClass(`ribbon-divider-${divider.id}`);
   this.dividerElements[divider.id] = dividerIconEl;
}
````

with following CSS:
```css
.side-dock-actions .side-dock-ribbon-action.ribbon-divider {
	height: 1px;
	width: 70%;
	padding: 4px 0;

	&:hover {
		background-color: transparent;
	}

	&:before {
		content: "";
		display: block;
		height: 1px;
		width: 100%;
		background-color: var(--icon-color);
		opacity: 0.5;
	}
}
```
