### ISSUE TITLE
Centered icons (maybe a toggle option?)

### ISSUE THREAD

**Issue by pedrovanderbeek** [gfxholo/iconic#71]
Made the switch from Iconize and I am really happy with everything except the alignment of the icons.
In iconize the icons are centered with the text, and in Iconic they align with the text height.
Might not be popular opinion, so would it be possible to make it a toggle or something like that?
Would be nice just to have that option, thank you so much.

**Comment by gfxholo** [comment]
Hey friend, I'm not really sure what you mean? Both plugins look equally centered on the vertical axis to me:

![#71](https://github.com/user-attachments/assets/9a7d319c-06ae-4c61-acea-0337b48798dc)

I screencapped the file explorer for this demo. Can you clarify what you'd like to see?

**Comment by pedrovanderbeek** [comment]
Hey bud, I'm sorry I didn't provide more info on it, I also double-checked, and this "issue" both applies to mobile and desktop.
I have provided an example below, colorized is Iconic and the other is Iconize.

Thank you!

![Image](https://github.com/user-attachments/assets/ac3082e9-4692-478d-9973-3e930cfb9d89)

**Comment by gfxholo** [comment]
Thanks, I see it! I think this is one of those off-by-1-pixel quirks which are hard to avoid at lower resolutions. The best solution is probably a CSS snippet which you can adjust to your own taste:

```css
.iconic-icon {
    translate: 0px -1px; /* horizontal pixels, vertical pixels */
}
```

If you only want sidebar icons to be affected:

```css
.workspace-leaf .iconic-icon {
    translate: 0px -1px; /* horizontal pixels, vertical pixels */
}
```

Hope this gets you a similar alignment :]
